version: "3.9"
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    command:
      - "postgres"
      - "-c"
      - "max_connections=300"
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
        - "${DB_PORT}:${DB_PORT}"

volumes:
  db_data: