version: "3.9"
services:
  app:
    container_name: expense_tracker_app
    build:
      context: ./
      dockerfile: ./Dockerfile
    networks:
      - backend_db
    expose:
      - 3000
    ports:
      - ${PORT}:3000
    restart: always
  db:
    image: postgres:12
    container_name: expense_tracker_db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    command:
      - "postgres"
      - "-c"
      - "max_connections=300"
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - ${DB_PORT}
    networks:
      - backend_db
    restart: always

networks:
  backend_db:


volumes:
  db_data:
