GET http://localhost:5000/api/expense

###

GET http://localhost:5000/api/expense/2

###

POST http://localhost:5000/api/expense

{
    "year": 2023,
    "month": 8,
    "amount": 55555,
    "category_id": 3
}

###

PUT http://localhost:5000/api/expense/2

{
    "year": 1976,
    "month": 3,
    "amount": 77777, 
    "category_id": 1
}

###

DELETE http://localhost:5000/api/expense/3




###

GET http://localhost:5000/api/category

###

GET http://localhost:5000/api/category/3

###

POST http://localhost:5000/api/category

{
    "name": "HSA"
}

###


PUT http://localhost:5000/api/category/3

{
    "name": "HSA: Reimburse"
}

###

DELETE http://localhost:5000/api/category/4


